import { BikeVaultData, ComponentCategory, UserSettings } from "@/types/vault";

export const DEFAULT_CATEGORIES: ComponentCategory[] = [
  { id: "cat-frame", code: "FRAME", nameCs: "Rám", nameEn: "Frame", defaultSlot: "FRAME", isSystem: true, sortOrder: 1 },
  { id: "cat-fork", code: "FORK", nameCs: "Vidlice", nameEn: "Fork", defaultSlot: "FORK", isSystem: true, sortOrder: 2 },
  { id: "cat-rear-shock", code: "REAR_SHOCK", nameCs: "Tlumič", nameEn: "Rear Shock", defaultSlot: "REAR_SHOCK", isSystem: true, sortOrder: 3 },
  { id: "cat-crankset", code: "CRANKSET", nameCs: "Kliky", nameEn: "Crankset", defaultSlot: "CRANKSET", isSystem: true, sortOrder: 4 },
  { id: "cat-bottom-bracket", code: "BOTTOM_BRACKET", nameCs: "Středové složení", nameEn: "Bottom Bracket", defaultSlot: "BOTTOM_BRACKET", isSystem: true, sortOrder: 5 },
  { id: "cat-rear-derailleur", code: "REAR_DERAILLEUR", nameCs: "Přehazovačka", nameEn: "Rear Derailleur", defaultSlot: "REAR_DERAILLEUR", isSystem: true, sortOrder: 6 },
  { id: "cat-cassette", code: "CASSETTE", nameCs: "Kazeta", nameEn: "Cassette", defaultSlot: "CASSETTE", isSystem: true, sortOrder: 7 },
  { id: "cat-chain", code: "CHAIN", nameCs: "Řetěz", nameEn: "Chain", defaultSlot: "CHAIN", isSystem: true, sortOrder: 8 },
  { id: "cat-shifter", code: "SHIFTER", nameCs: "Řazení", nameEn: "Shifter", defaultSlot: "SHIFTER", isSystem: true, sortOrder: 9 },
  { id: "cat-brakes", code: "BRAKES", nameCs: "Brzdy", nameEn: "Brakes", defaultSlot: "BRAKES", isSystem: true, sortOrder: 10 },
  { id: "cat-brake-rotors", code: "BRAKE_ROTORS", nameCs: "Brzdové kotouče", nameEn: "Brake Rotors", defaultSlot: "BRAKE_ROTORS", isSystem: true, sortOrder: 11 },
  { id: "cat-brake-pads", code: "BRAKE_PADS", nameCs: "Brzdové destičky", nameEn: "Brake Pads", defaultSlot: "BRAKE_PADS", isSystem: true, sortOrder: 12 },
  { id: "cat-wheels", code: "WHEELS", nameCs: "Kola / Výplety", nameEn: "Wheels", defaultSlot: "WHEELS", isSystem: true, sortOrder: 13 },
  { id: "cat-tire-front", code: "TIRE_FRONT", nameCs: "Přední plášť", nameEn: "Front Tire", defaultSlot: "FRONT_TIRE", isSystem: true, sortOrder: 14 },
  { id: "cat-tire-rear", code: "TIRE_REAR", nameCs: "Zadní plášť", nameEn: "Rear Tire", defaultSlot: "REAR_TIRE", isSystem: true, sortOrder: 15 },
  { id: "cat-handlebar", code: "HANDLEBAR", nameCs: "Řídítka", nameEn: "Handlebar", defaultSlot: "HANDLEBAR", isSystem: true, sortOrder: 16 },
  { id: "cat-stem", code: "STEM", nameCs: "Představec", nameEn: "Stem", defaultSlot: "STEM", isSystem: true, sortOrder: 17 },
  { id: "cat-headset", code: "HEADSET", nameCs: "Hlavové složení", nameEn: "Headset", defaultSlot: "HEADSET", isSystem: true, sortOrder: 18 },
  { id: "cat-seatpost", code: "SEATPOST", nameCs: "Sedlovka", nameEn: "Seatpost", defaultSlot: "SEATPOST", isSystem: true, sortOrder: 19 },
  { id: "cat-saddle", code: "SADDLE", nameCs: "Sedlo", nameEn: "Saddle", defaultSlot: "SADDLE", isSystem: true, sortOrder: 20 },
  { id: "cat-pedals", code: "PEDALS", nameCs: "Pedály", nameEn: "Pedals", defaultSlot: "PEDALS", isSystem: true, sortOrder: 21 },
  { id: "cat-other", code: "OTHER", nameCs: "Ostatní", nameEn: "Other", defaultSlot: "OTHER", isSystem: true, sortOrder: 99 },
];

export const DEFAULT_SETTINGS: UserSettings = {
  currency: "CZK",
  distanceUnit: "km",
  language: "cs",
  googleClientId: "471929194107-leupf0slff3no70bl5u7104aaim5jcmf.apps.googleusercontent.com",
};

export const INITIAL_VAULT_DATA: BikeVaultData = {
  version: 1,
  updatedAt: "2026-09-13T12:00:00.000Z",
  categories: DEFAULT_CATEGORIES,
  settings: DEFAULT_SETTINGS,
  bikes: [
    {
      id: "bike-propain-spindrift",
      name: "Propain Spindrift CF",
      manufacturer: "Propain",
      model: "Spindrift CF",
      modelYear: 2024,
      category: "MTB",
      discipline: "ENDURO",
      suspensionType: "FULL_SUSPENSION",
      driveType: "CONVENTIONAL",
      serialNumber: "PROP-SPIN-2024-8841",
      purchaseDate: "2024-03-15",
      purchasePrice: 145000,
      currency: "CZK",
      status: "ACTIVE",
      currentKm: 2847.0,
      currentMinutes: 11160, // 186 h
      imageUrl: "https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?auto=format&fit=crop&w=1200&q=80",
      notes: "Zakázková stavba z Německa. Využití: bikeparky, enduro závody a těžké traily.",
      createdAt: "2024-03-15T10:00:00.000Z",
      updatedAt: "2026-09-13T12:00:00.000Z",
    },
    {
      id: "bike-canyon-grizl",
      name: "Canyon Grizl 7 Suspension",
      manufacturer: "Canyon",
      model: "Grizl 7 Suspension",
      modelYear: 2023,
      category: "GRAVEL",
      discipline: "GRAVEL",
      suspensionType: "FRONT_SUSPENSION",
      driveType: "CONVENTIONAL",
      serialNumber: "CYN-GRIZL-2023-1029",
      purchaseDate: "2023-08-10",
      purchasePrice: 62000,
      currency: "CZK",
      status: "ACTIVE",
      currentKm: 4210.0,
      currentMinutes: 13800, // 230 h
      imageUrl: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=1200&q=80",
      notes: "Univerzál na šotoliny, bikepacking a zimní tréninky. Odpružená vidlice Rudy 30mm.",
      createdAt: "2023-08-10T10:00:00.000Z",
      updatedAt: "2026-09-13T12:00:00.000Z",
    },
  ],
  odometerEntries: [
    {
      id: "odo-propain-init",
      bikeId: "bike-propain-spindrift",
      recordedAt: "2024-03-15T10:00:00.000Z",
      entryDate: "2024-03-15",
      entryType: "INITIAL",
      deltaKm: 0,
      deltaMinutes: 0,
      resultingKm: 0,
      resultingMinutes: 0,
      note: "Nově pořízené kolo",
      createdAt: "2024-03-15T10:00:00.000Z",
    },
    {
      id: "odo-propain-snapshot1",
      bikeId: "bike-propain-spindrift",
      recordedAt: "2024-06-01T18:00:00.000Z",
      entryDate: "2024-06-01",
      entryType: "RIDE",
      deltaKm: 1200,
      deltaMinutes: 4800,
      resultingKm: 1200,
      resultingMinutes: 4800,
      note: "Pravidelný odečet před dovolenou",
      createdAt: "2024-06-01T18:00:00.000Z",
    },
    {
      id: "odo-propain-snapshot2",
      bikeId: "bike-propain-spindrift",
      recordedAt: "2024-09-11T12:00:00.000Z",
      entryDate: "2024-09-11",
      entryType: "RIDE",
      deltaKm: 1647,
      deltaMinutes: 6360,
      resultingKm: 2847,
      resultingMinutes: 11160,
      note: "Konec léta, kontrola před servisem",
      createdAt: "2024-09-11T12:00:00.000Z",
    },
    {
      id: "odo-grizl-init",
      bikeId: "bike-canyon-grizl",
      recordedAt: "2023-08-10T10:00:00.000Z",
      entryDate: "2023-08-10",
      entryType: "INITIAL",
      deltaKm: 0,
      deltaMinutes: 0,
      resultingKm: 0,
      resultingMinutes: 0,
      note: "Nově pořízené kolo",
      createdAt: "2023-08-10T10:00:00.000Z",
    },
    {
      id: "odo-grizl-snapshot",
      bikeId: "bike-canyon-grizl",
      recordedAt: "2024-08-20T17:00:00.000Z",
      entryDate: "2024-08-20",
      entryType: "RIDE",
      deltaKm: 4210,
      deltaMinutes: 13800,
      resultingKm: 4210,
      resultingMinutes: 13800,
      note: "Bikepacking Rakousko + celoroční ježdění",
      createdAt: "2024-08-20T17:00:00.000Z",
    },
  ],
  components: [
    {
      id: "comp-zeb",
      categoryId: "cat-fork",
      manufacturer: "RockShox",
      model: "ZEB Ultimate Charger 3.1 RC2",
      variant: "Slab Grey 180mm 29\"",
      serialNumber: "RS-ZEB-2024-9912",
      initialKm: 0,
      initialMinutes: 0,
      purchaseDate: "2024-05-02",
      purchasePrice: 24900,
      currency: "CZK",
      status: "INSTALLED",
      notes: "Upgrade z původní vidlice ZEB Select.",
      createdAt: "2024-05-02T10:00:00.000Z",
      updatedAt: "2026-09-13T12:00:00.000Z",
    },
    {
      id: "comp-superdeluxe",
      categoryId: "cat-rear-shock",
      manufacturer: "RockShox",
      model: "Super Deluxe Ultimate RC2T",
      variant: "Air 205x65 Trunnion",
      serialNumber: "RS-SD-2024-4411",
      initialKm: 0,
      initialMinutes: 0,
      purchaseDate: "2024-03-15",
      purchasePrice: 15500,
      currency: "CZK",
      status: "INSTALLED",
      notes: "Hydraulic Bottom Out, lineární vzduchová komora.",
      createdAt: "2024-03-15T10:00:00.000Z",
      updatedAt: "2026-09-13T12:00:00.000Z",
    },
    {
      id: "comp-chain-sram-xx",
      categoryId: "cat-chain",
      manufacturer: "SRAM",
      model: "XX Eagle Transmission Flattop",
      variant: "126 článků",
      serialNumber: "SRAM-XX-1120",
      initialKm: 0,
      initialMinutes: 0,
      purchaseDate: "2024-03-15",
      purchasePrice: 3200,
      currency: "CZK",
      status: "INSTALLED",
      createdAt: "2024-03-15T10:00:00.000Z",
      updatedAt: "2026-09-13T12:00:00.000Z",
    },
    {
      id: "comp-chain-sram-xx-spare",
      categoryId: "cat-chain",
      manufacturer: "SRAM",
      model: "XX Eagle Transmission Flattop",
      variant: "126 článků",
      serialNumber: "SRAM-XX-SPARE-1",
      initialKm: 0,
      initialMinutes: 0,
      purchaseDate: "2024-06-10",
      purchasePrice: 2890,
      currency: "CZK",
      status: "IN_STORAGE",
      notes: "Náhradní řetěz připravený ve skladu pro rychlou výměnu.",
      createdAt: "2024-06-10T10:00:00.000Z",
      updatedAt: "2026-09-13T12:00:00.000Z",
    },
    {
      id: "comp-assegai-front",
      categoryId: "cat-tire-front",
      manufacturer: "Maxxis",
      model: "Assegai",
      variant: "3C MaxxGrip EXO+ TR",
      wheelDiameter: "29",
      tireWidth: "2.50 WT",
      tireCasing: "EXO+",
      tireCompound: "3C MaxxGrip",
      isTubeless: true,
      initialKm: 0,
      initialMinutes: 0,
      purchaseDate: "2024-03-15",
      purchasePrice: 1890,
      currency: "CZK",
      status: "INSTALLED",
      createdAt: "2024-03-15T10:00:00.000Z",
      updatedAt: "2026-09-13T12:00:00.000Z",
    },
    {
      id: "comp-dhr-rear",
      categoryId: "cat-tire-rear",
      manufacturer: "Maxxis",
      model: "Minion DHR II",
      variant: "3C MaxxTerra DoubleDown TR",
      wheelDiameter: "29",
      tireWidth: "2.40 WT",
      tireCasing: "DoubleDown",
      tireCompound: "3C MaxxTerra",
      isTubeless: true,
      initialKm: 0,
      initialMinutes: 0,
      purchaseDate: "2024-03-15",
      purchasePrice: 1990,
      currency: "CZK",
      status: "INSTALLED",
      createdAt: "2024-03-15T10:00:00.000Z",
      updatedAt: "2026-09-13T12:00:00.000Z",
    },
    {
      id: "comp-rudy-fork",
      categoryId: "cat-fork",
      manufacturer: "RockShox",
      model: "Rudy Ultimate XPLR",
      variant: "30mm Travel 700c",
      serialNumber: "RS-RUDY-2023-0199",
      initialKm: 0,
      initialMinutes: 0,
      purchaseDate: "2023-08-10",
      purchasePrice: 17500,
      currency: "CZK",
      status: "INSTALLED",
      createdAt: "2023-08-10T10:00:00.000Z",
      updatedAt: "2026-09-13T12:00:00.000Z",
    },
    {
      id: "comp-grx-rear-der",
      categoryId: "cat-rear-derailleur",
      manufacturer: "Shimano",
      model: "GRX RD-RX812",
      variant: "1x11 Shadow RD+",
      initialKm: 0,
      initialMinutes: 0,
      purchaseDate: "2023-08-10",
      purchasePrice: 2800,
      currency: "CZK",
      status: "INSTALLED",
      createdAt: "2023-08-10T10:00:00.000Z",
      updatedAt: "2026-09-13T12:00:00.000Z",
    },
  ],
  componentInstallations: [
    {
      id: "inst-zeb",
      bikeId: "bike-propain-spindrift",
      componentId: "comp-zeb",
      slot: "FORK",
      installedAt: "2024-05-02T10:00:00.000Z",
      installedBikeKm: 747,
      installedBikeMinutes: 3000,
      createdAt: "2024-05-02T10:00:00.000Z",
    },
    {
      id: "inst-superdeluxe",
      bikeId: "bike-propain-spindrift",
      componentId: "comp-superdeluxe",
      slot: "REAR_SHOCK",
      installedAt: "2024-03-15T10:00:00.000Z",
      installedBikeKm: 0,
      installedBikeMinutes: 0,
      createdAt: "2024-03-15T10:00:00.000Z",
    },
    {
      id: "inst-chain-propain",
      bikeId: "bike-propain-spindrift",
      componentId: "comp-chain-sram-xx",
      slot: "CHAIN",
      installedAt: "2024-03-15T10:00:00.000Z",
      installedBikeKm: 0,
      installedBikeMinutes: 0,
      createdAt: "2024-03-15T10:00:00.000Z",
    },
    {
      id: "inst-assegai-propain",
      bikeId: "bike-propain-spindrift",
      componentId: "comp-assegai-front",
      slot: "FRONT_TIRE",
      installedAt: "2024-03-15T10:00:00.000Z",
      installedBikeKm: 0,
      installedBikeMinutes: 0,
      createdAt: "2024-03-15T10:00:00.000Z",
    },
    {
      id: "inst-dhr-propain",
      bikeId: "bike-propain-spindrift",
      componentId: "comp-dhr-rear",
      slot: "REAR_TIRE",
      installedAt: "2024-03-15T10:00:00.000Z",
      installedBikeKm: 0,
      installedBikeMinutes: 0,
      createdAt: "2024-03-15T10:00:00.000Z",
    },
    {
      id: "inst-rudy-grizl",
      bikeId: "bike-canyon-grizl",
      componentId: "comp-rudy-fork",
      slot: "FORK",
      installedAt: "2023-08-10T10:00:00.000Z",
      installedBikeKm: 0,
      installedBikeMinutes: 0,
      createdAt: "2023-08-10T10:00:00.000Z",
    },
    {
      id: "inst-grx-grizl",
      bikeId: "bike-canyon-grizl",
      componentId: "comp-grx-rear-der",
      slot: "REAR_DERAILLEUR",
      installedAt: "2023-08-10T10:00:00.000Z",
      installedBikeKm: 0,
      installedBikeMinutes: 0,
      createdAt: "2023-08-10T10:00:00.000Z",
    },
  ],
  serviceSchedules: [
    {
      id: "sched-zeb-lower-50h",
      bikeId: "bike-propain-spindrift",
      componentId: "comp-zeb",
      name: "Servis spodních nohou vidlice",
      intervalHours: 50,
      conditionType: "WHICHEVER_FIRST",
      warningThresholdHours: 5,
      lastServiceDate: "2024-07-20",
      lastServiceBikeKm: 2100.0,
      lastServiceBikeHours: 143.0,
      isActive: true,
      createdAt: "2024-05-02T10:00:00.000Z",
    },
    {
      id: "sched-superdeluxe-200h",
      bikeId: "bike-propain-spindrift",
      componentId: "comp-superdeluxe",
      name: "Kompletní servis tlumiče (200 h)",
      intervalHours: 200,
      conditionType: "WHICHEVER_FIRST",
      warningThresholdHours: 15,
      lastServiceDate: "2024-03-15",
      lastServiceBikeKm: 0,
      lastServiceBikeHours: 0,
      isActive: true,
      createdAt: "2024-03-15T10:00:00.000Z",
    },
    {
      id: "sched-chain-check",
      bikeId: "bike-propain-spindrift",
      componentId: "comp-chain-sram-xx",
      name: "Výměna řetězu Eagle Transmission",
      intervalKm: 1500,
      conditionType: "WHICHEVER_FIRST",
      lastServiceDate: "2024-05-15",
      lastServiceBikeKm: 1204.0,
      lastServiceBikeHours: 78.0,
      isActive: true,
      createdAt: "2024-03-15T10:00:00.000Z",
    },
  ],
  serviceEvents: [
    {
      id: "se-zeb-lower-legs",
      serviceScheduleId: "sched-zeb-lower-50h",
      bikeId: "bike-propain-spindrift",
      componentId: "comp-zeb",
      eventType: "MAINTENANCE",
      serviceDate: "2024-07-20",
      bikeKm: 2100.0,
      bikeMinutes: 8580, // 143 h
      performedBy: "SELF",
      description: "Výměna oleje ve spodních nohách (Maxima Plush Dynamic Heavy), nová stírací těsnění SKF.",
      laborPrice: 0,
      partsPrice: 850,
      totalPrice: 850,
      currency: "CZK",
      notes: "Gufera v pořádku, kluzáky bez poškození.",
      createdAt: "2024-07-20T16:00:00.000Z",
    },
  ],
  bikeSetups: [
    {
      id: "setup-propain",
      bikeId: "bike-propain-spindrift",
      forkInstallationId: "inst-zeb",
      shockInstallationId: "inst-superdeluxe",
      frontTireInstallationId: "inst-assegai-propain",
      rearTireInstallationId: "inst-dhr-propain",
      forkPressurePsi: 68.0,
      forkSagPercent: 28,
      forkReboundClicks: 9,
      forkLscClicks: 8,
      forkHscClicks: 3,
      forkVolumeSpacers: 1,
      forkTravelMm: 180,
      forkNotes: "Základní setup pro bikepark. Odskok počítán od plně zavřené polohy.",
      shockPressurePsi: 185.0,
      shockSagPercent: 30,
      shockReboundClicks: 6,
      shockLscClicks: 4,
      shockHscClicks: 2,
      shockVolumeSpacers: 2,
      shockNotes: "Progresivní nastavení pro skoky.",
      frontTirePressureBar: 1.55,
      frontTireInsert: "CushCore PRO",
      frontTireNotes: "Tlak pro suché a kořenité traily.",
      rearTirePressureBar: 1.85,
      rearTireInsert: "CushCore PRO",
      rearTireNotes: "Vyšší tlak kvůli ochraně ráfku na kamenech.",
      generalNotes: "Setup laděn v bikeparku Špičák a Geisskopf.",
      updatedAt: "2026-09-13T12:00:00.000Z",
    },
    {
      id: "setup-grizl",
      bikeId: "bike-canyon-grizl",
      forkInstallationId: "inst-rudy-grizl",
      forkPressurePsi: 110.0,
      forkSagPercent: 20,
      forkReboundClicks: 12,
      frontTirePressureBar: 2.3,
      rearTirePressureBar: 2.6,
      generalNotes: "Setup pro celodenní gravel trasy s brašnami.",
      updatedAt: "2026-09-13T12:00:00.000Z",
    },
  ],
  setupSnapshots: [
    {
      id: "snap-propain-park",
      bikeId: "bike-propain-spindrift",
      profileName: "Bikepark & Skoky",
      snapshotData: {
        forkPressurePsi: 72.0,
        forkReboundClicks: 8,
        shockPressurePsi: 195.0,
        shockReboundClicks: 5,
        frontTirePressureBar: 1.65,
        rearTirePressureBar: 1.95,
      },
      notes: "Tvrdší nastavení na velké skoky a dopady.",
      createdAt: "2024-06-15T14:00:00.000Z",
    },
  ],
  financialTransactions: [
    {
      id: "fin-propain-purchase",
      bikeId: "bike-propain-spindrift",
      type: "EXPENSE",
      category: "BIKE_PURCHASE",
      amount: 145000,
      currency: "CZK",
      transactionDate: "2024-03-15",
      notes: "Nákup kompletního kola Propain Spindrift CF",
      createdAt: "2024-03-15T10:00:00.000Z",
    },
    {
      id: "fin-zeb-upgrade",
      bikeId: "bike-propain-spindrift",
      componentId: "comp-zeb",
      type: "EXPENSE",
      category: "UPGRADE",
      amount: 24900,
      currency: "CZK",
      transactionDate: "2024-05-02",
      notes: "Upgrade na vidlici RockShox ZEB Ultimate Charger 3.1",
      createdAt: "2024-05-02T10:00:00.000Z",
    },
    {
      id: "fin-zeb-service",
      bikeId: "bike-propain-spindrift",
      componentId: "comp-zeb",
      serviceEventId: "se-zeb-lower-legs",
      type: "EXPENSE",
      category: "SERVICE_PARTS",
      amount: 850,
      currency: "CZK",
      transactionDate: "2024-07-20",
      notes: "Servisní sada těsnění a olej pro ZEB",
      createdAt: "2024-07-20T16:00:00.000Z",
    },
    {
      id: "fin-grizl-purchase",
      bikeId: "bike-canyon-grizl",
      type: "EXPENSE",
      category: "BIKE_PURCHASE",
      amount: 62000,
      currency: "CZK",
      transactionDate: "2023-08-10",
      notes: "Nákup kola Canyon Grizl 7 Suspension",
      createdAt: "2023-08-10T10:00:00.000Z",
    },
  ],
};
